app/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', array('uses' => 'HomeController@showLogin'));
Route::get('login', array('as' => 'login', function () { }));
Route::get('register', function()
{
	return View::make('contractors.create');
});  

 Route::get('register', array(
  'uses' => 'ContractorsController@create',
  'as' => 'contractors.create'
));  
Route::get('agreement', array('as' => 'agreement', function () { return View::make('agreement'); }));
 Route::post('projectinfo', array(
  'uses' => 'ProjectsController@projectinfo',
  'as' => 'projects.projectinfo'
))->before('auth'); 

Route::post('projectjobtype', array(
  'uses' => 'ProjectsController@projectjobtype',
   'as' => 'projects.projectjobtype'
))->before('auth');  
Route::post('updatedescription', array(
  'uses' => 'ProjectsController@updatedescription',
   'as' => 'projects.updatedescription'
))->before('auth');  
Route::get('projects/{id}/clientprojects', 'ProjectsController@clientprojects')->before('auth');
Route::get('taskcategories/{id}/defaltctry', 'TaskcategoriesController@defaltctry')->before('auth');
Route::get('jobtypes/{id}/updatesdefault', 'JobtypesController@updatesdefault')->before('auth');

Route::get('estimates/{id}/download', 'EstimatesController@download')->before('auth');

Route::get('projects/{id}/delete', 'ProjectsController@delete')->before('auth');

Route::get('projects/{id}/deletesepc', 'ProjectsController@deletesepc')->before('auth');

Route::get('projects/{id}/showsepc', 'ProjectsController@showsepc')->before('auth');

Route::get('invoices/{id}/download', 'InvoicesController@download')->before('auth');

Route::get('resources/{id}/download', 'ResourcesController@download')->before('auth');

Route::get('notes/{id}/destroy', 'NotesController@destroy')->before('auth');

Route::get('projects/{id}/spec', 'ProjectsController@spec')->before('auth');

Route::get('projects/{id}/projecthistory', 'ProjectsController@projecthistory')->before('auth');

Route::get('clients/{id}/send', 'ClientsController@send')->before('auth');

///Route::get('clients/{id}/emailsend', 'ClientsController@emailsend')->before('auth');

 Route::post('emailsend', array(
  'uses' => 'ClientsController@emailsend',
   'as' => 'ClientsController.emailsend'
))->before('auth');

	//Route::get('dashboard', array('as' => 'dashboard', function () { return View::make('dashboard'); }))->before('auth');
	//Route::get('admin', array('as' => 'admin', function () { return View::make('admin'); }))->before('auth');
	
	Route::get('admin', array('uses' => 'HomeController@showAdmin'));
	Route::get('dashboard', array('uses' => 'HomeController@showLogin'));									

	//Route::resource('contractors', 'ContractorsController');
Route::group(array('before' => 'auth'), function()
{

	//echo Hash::make("3deufosm");
	//echo Hash::make("contractor");
		

		 Route::get('contractors/{id}/editadmin', array(
		  'uses' => 'ContractorsController@editadmin',
		  'as' => 'contractors.editadmin'
		 )); 

		Route::get('contractors/{id}/editadmin', 'ContractorsController@editadmin')->before('auth');
		Route::resource('units', 'UnitsController');
		Route::resource('contractors', 'ContractorsController');
		Route::resource('clients', 'ClientsController');
		Route::resource('jobtypes', 'JobtypesController');
		Route::resource('taskcategories', 'TaskcategoriesController');
		Route::resource('tasks', 'TasksController');
		Route::resource('projects', 'ProjectsController');
		Route::resource('estimates', 'EstimatesController');
		Route::resource('invoices', 'InvoicesController');
		Route::resource('resources', 'ResourcesController');
		Route::resource('notes', 'NotesController');
		Route::resource('projecttypes', 'ProjecttypesController');
});

// route to show the login form 
Route::get('login', array('uses' => 'HomeController@showLogin'));
// route to process the form
Route::post('login', array('uses' => 'HomeController@doLogin'));
Route::get('logout', array('uses' => 'HomeController@doLogout'));
 Route::post('create', array(
  'uses' => 'ContractorsController@store',
  'as' => 'contractors.store'
));
//Route::get('getremind', array('uses' => 'RemindersController@getRemind'));
Route::get('password/reset', array(
  'uses' => 'RemindersController@getRemind',
  'as' => 'password.remind'
));
 Route::get('updatespecification', array(
		  'uses' => 'ProjectsController@updatespecification',
		  'as' => 'ProjectsController.updatespecification'
		 )); 
 Route::get('updatespecarchive', array(
		  'uses' => 'ProjectsController@updatespecarchive',
		  'as' => 'ProjectsController.updatespecarchive'
		 )); 		 
Route::get('description', array(
	  'uses' => 'ProjectsController@description',
	  'as' => 'ProjectsController.description'
	 ));  
Route::get('historydescription', array(
	  'uses' => 'ProjectsController@historydescription',
	  'as' => 'ProjectsController.historydescriptions'
	 )); 	 
/*
/ Forgot password (POST)
 */
 Route::post('/password/forgot-password', array(
	'as' => 'forgot-password-post',
	'uses' => 'PasswordController@postForgotPassword'
	));
	
/*
/ Forgot password (GET)
 */
 Route::get('/password/forgot-password', array(
	'as' => 'forgot-password',
	'uses' => 'PasswordController@getForgotPassword'
	));
	
Route::get('/password/recover/{code}', array(
	'as' => 'recover-password',
	'uses' => 'PasswordController@getRecoverPassword'

	));	
 Route::get('changepassword', array(
		  'uses' => 'ContractorsController@changepassword',
		  'as' => 'contractors.changepassword'
		 ))->before('auth');
Route::get('billingifo', array(
		  'uses' => 'ContractorsController@billingifo',
		  'as' => 'contractors.billingifo'
		 ))->before('auth');		 
Route::post('storepassword', array(
	'uses' => 'ContractorsController@storepassword',
	'as' => 'contractors.storepassword'
))->before('auth'); 
Route::post('storebillingifo', array(
	'uses' => 'ContractorsController@storebillingifo',
	'as' => 'contractors.storebillingifo'
))->before('auth'); 
/**
Route::get('notes-alert', array(
		  'uses' => 'RemindersController@notesReminder',
		  'as' => 'reminders.notesalert'
		 )); **/

app/views/estimates/create.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Create Estimate</h1>

{{ Form::open(array('route' => 'estimates.store')) }}
	<ul>
        <li>
            {{ Form::label('title', 'Title:') }}
            {{ Form::text('title') }}
        </li>

        <li>
            {{ Form::label('file', 'File:') }}
            {{ Form::text('file') }}
        </li>

        <li>
            {{ Form::label('contractorid', 'Contractorid:') }}
            {{ Form::input('number', 'contractorid') }}
        </li>

        <li>
            {{ Form::label('projectid', 'Projectid:') }}
            {{ Form::input('number', 'projectid') }}
        </li>

		<li>
			{{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
		</li>
	</ul>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/estimates/edit.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Edit Estimate</h1>
{{ Form::model($estimate, array('method' => 'PATCH', 'route' => array('estimates.update', $estimate->id))) }}
	<ul>
        <li>
            {{ Form::label('title', 'Title:') }}
            {{ Form::text('title') }}
        </li>

        <li>
            {{ Form::label('file', 'File:') }}
            {{ Form::text('file') }}
        </li>

        <li>
            {{ Form::label('contractorid', 'Contractorid:') }}
            {{ Form::input('number', 'contractorid') }}
        </li>

        <li>
            {{ Form::label('projectid', 'Projectid:') }}
            {{ Form::input('number', 'projectid') }}
        </li>

		<li>
			{{ Form::submit('Update', array('class' => 'btn btn-info')) }}
			{{ link_to_route('estimates.show', 'Cancel', $estimate->id, array('class' => 'btn')) }}
		</li>
	</ul>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/estimates/index.blade.php
@extends('layouts.user')

@section('main')
<div class="viewproject">
	<section class="content">
			<div class="main">
				<div class="content-top">
					<div class="title-page left">
						<h2>Estimates</h2>
						<div class="breadcrumb">
							<a href="{{{ URL::to('/dashboard') }}}" class="home"><img src="{{ URL::asset('assets/images/home-icon.png') }}" alt=""/></a>
							<a href="{{{ URL::to('/dashboard') }}}">Dashboard</a>
							<span>></span>
                     <span>Estimates</span>
						</div>
					</div><!--title-page-->
				</div><!--top-content-->	
				<div class="content-body">
					<article class="shadow right">
						@if (count($estimates))
						<ul class="title-list">
                        <li>
                            <span style="width:18%" class="name">Estimate Title</span>
							<span style="width:18%" class="name">Project Name</span>
                            <span style="width:10%" class="date">Date Created</span>
							<span style="width:8%" class="date">Proposal No.</span>
							<span style="width:8%" class="date">Total</span>
                        </li>
                   </ul>
                   <ul class="body-list">
                   		@foreach ($estimates as $estimate)
                        <li>
                        	<span style="width:18%" class="name">{{ $estimate->title }}</span>
							<span style="width:18%" class="name">{{ Project::where('id',$estimate->projectid)->Pluck('name');}}</span>
							<span style="width:10%" class="date">{{ date("M d, Y", strtotime($estimate->created_at)) }}</span>
							<span style="width:8%" class="date">{{ $estimate->proposal }}</span>
                            <span style="width:8%" class="date" style="border-right:none;">{{ str_replace('$-','-$','$'.number_format($estimate->total, 2)) }}</span>
							
							<span style="width:auto" class="link">
								<select name="pdf_option_{{ $estimate->id }}" id="pdf_option_{{ $estimate->id }}" >
									<option value='0'>Download with Logo</option>
									<option value='1'>Download without Logo</option>
								</select>
								<a onclick='downloadEstimate( {{ $estimate->id }} )' style="text-decoration:underline">Download</a> | 
							
								<a href="{{ URL::to('projects/'.$estimate->id.'/showsepc?id='.$estimate->projectid.'&urls=estimates') }}" style="text-decoration:underline">View Estimate</a> | 
							
								{{ Form::open(array('method' => 'DELETE','onsubmit'=>'return confirmDelete()','id'=>'delete', 'style'=>'display: inline-block; width: 45px; float: none;', 'route' => array('estimates.destroy', $estimate->id))) }}
									{{ Form::hidden('projects',$estimate->projectid) }}
									{{ Form::hidden('urls','estimates') }} 
									{{ Form::submit('Delete', array('class'=>'deleting')) }}
								{{ Form::close() }}
							</span>
							
                        </li>
                        @endforeach
                    </ul>
					{{ $estimates->links() }}
                    @else
								<div class="row">
                        	<div class="success">There are no Estimates</div><!--success-->
                    		</div><!--row-->
						  @endif    
					</article>
				</div>		
			</div>
	</section>
</div>
<script>
function downloadEstimate(id){

	var op = document.getElementById('pdf_option_'+id).value;
	window.location="<?php echo  URL::to('estimates') ?>/"+id+"/download?logo="+op;
}
</script>
@stop

app/views/estimates/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Show Estimate</h1>

<p>{{ link_to_route('estimates.index', 'Return to all estimates') }}</p>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Title</th>
				<th>File</th>
				<th>Contractorid</th>
				<th>Projectid</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $estimate->title }}}</td>
					<td>{{{ $estimate->file }}}</td>
					<td>{{{ $estimate->contractorid }}}</td>
					<td>{{{ $estimate->projectid }}}</td>
                    <td>{{ link_to_route('estimates.edit', 'Edit', array($estimate->id), array('class' => 'btn btn-info')) }}</td>
                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('estimates.destroy', $estimate->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>
		</tr>
	</tbody>
</table>

@stop